.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH WMIFINFO 1 "June  7, 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
wmifinfo \- dockapp for showing basic network info for all available interfaces
.SH SYNOPSIS
.B wmifinfo
.RI [-lh] [-i interface]

This manual page documents briefly the
.B wmifinfo
command.
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has documentation in the GNU Info format; see below.
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
\fBwmifinfo\fP is is a simple applet showing basic network info for all
available interfaces. 
It shows IP address, netmask, gateway and MAC address. A bit like ifconfig.
Left-button click moves to the next interface, right-button click calls
ifup/ifdown scripts. 
Please report bugs if you find any.
.SH OPTIONS
A summary of options is included below.
.TP
.B \-h
Show summary of options.
.TP
.B \-v
Show version of program.
.TP
.B \-d <cmd>
Command to exec for iface-down
.TP
.B \-i <interface>
Start with given interface, if available
.TP
.B \-l
LCD display mode
.TP
.B \-u
Command to exec for iface-up
.br
.SH AUTHOR
This manual page was written by Søren Boll Overgaard <boll@debian.org>,
for the Debian GNU/Linux system (but may be used by others).
